#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import re
from pathlib import Path


BLOCK_PREFIXES = {"0.0.0.0", "127.0.0.1", "::1"}
HOSTNAME_RE = re.compile(
    r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)(?:\.(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?))*$"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a local hosts file with all redirect IPs replaced by cms/ams IPs"
    )
    parser.add_argument("--input", required=True, help="Path to source hosts file")
    parser.add_argument("--cms-ip", required=True, help="Replacement IP for cms node")
    parser.add_argument("--ams-ip", required=True, help="Replacement IP for ams node")
    parser.add_argument(
        "--overrides",
        help="Optional JSON file with force_nodes mapping: hostname -> cms|ams",
    )
    parser.add_argument("--output", required=True, help="Path to generated hosts file")
    return parser.parse_args()


def normalize_line(line: str) -> tuple[str, str] | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None

    parts = stripped.split()
    if len(parts) < 2:
        return None

    ip = parts[0].strip()
    host = parts[1].strip().lower()
    if not host or host in {"localhost", "ip6-localhost"}:
        return None
    if not HOSTNAME_RE.fullmatch(host):
        return None

    try:
        ipaddress.ip_address(ip)
    except ValueError:
        return None

    return ip, host


def load_overrides(overrides_path: str | None) -> dict[str, str]:
    if not overrides_path:
        return {}

    payload = json.loads(Path(overrides_path).read_text(encoding="utf-8"))
    force_nodes = payload.get("force_nodes", {})
    if not isinstance(force_nodes, dict):
        raise ValueError("force_nodes must be an object")

    overrides: dict[str, str] = {}
    for raw_host, raw_node in force_nodes.items():
        host = str(raw_host).strip().lower()
        node = str(raw_node).strip().lower()
        if not HOSTNAME_RE.fullmatch(host):
            raise ValueError(f"Invalid override hostname: {raw_host}")
        if node not in {"cms", "ams"}:
            raise ValueError(f"Invalid override node for {host}: {raw_node}")
        overrides[host] = node

    return overrides


def select_redirect_ip(host: str, cms_ip: str, ams_ip: str, overrides: dict[str, str]) -> str:
    forced_node = overrides.get(host)
    if forced_node == "cms":
        return cms_ip
    if forced_node == "ams":
        return ams_ip

    digest = hashlib.sha256(host.encode("utf-8")).digest()
    return cms_ip if digest[0] % 2 == 0 else ams_ip


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ipaddress.ip_address(args.cms_ip)
    ipaddress.ip_address(args.ams_ip)
    overrides = load_overrides(args.overrides)

    rendered: list[str] = []
    seen: set[str] = set()

    for raw_line in input_path.read_text(encoding="utf-8").splitlines():
        normalized = normalize_line(raw_line)
        if normalized is None:
            continue

        ip, host = normalized
        if ip in BLOCK_PREFIXES:
            line = f"0.0.0.0 {host}"
        else:
            remapped_ip = select_redirect_ip(host, args.cms_ip, args.ams_ip, overrides)
            line = f"{remapped_ip} {host}"

        if line in seen:
            continue
        seen.add(line)
        rendered.append(line)

    output_path.write_text(
        "\n".join(
            [
                "# Generated by DnsConf custom hosts generator",
                f"# Source: {input_path.name}",
                f"# cms_ip: {args.cms_ip}",
                f"# ams_ip: {args.ams_ip}",
                f"# overrides: {args.overrides or 'none'}",
                "# Redirect domains use force_nodes overrides first, then deterministic hostname hash fallback",
                *rendered,
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Generated {len(rendered)} records into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
