#!/usr/bin/env python3

from __future__ import annotations

import argparse
import ipaddress
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path


DEFAULT_SOURCES = [
    "https://dns.geohide.ru:8443",
    "https://info.dns.malw.link/hosts",
    "https://iplist.opencck.org/ru",
    "https://freedom.mafioznik.xyz/file/hosts",
]

BLOCK_PREFIXES = {"0.0.0.0", "127.0.0.1", "::1"}
RAW_HOSTS_URL_RE = re.compile(r"https://raw\.githubusercontent\.com/[^\s\"'<>]+/hosts")
HOSTNAME_RE = re.compile(
    r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)(?:\.(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?))*$"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build merged hosts source file")
    parser.add_argument("--output", required=True, help="Path to generated hosts file")
    parser.add_argument(
        "--source",
        action="append",
        dest="sources",
        help="Hosts source URL. Can be repeated. Defaults to the built-in source list.",
    )
    return parser.parse_args()


def fetch(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "DnsConf-hosts-generator/1.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def resolve_hosts_content(url: str) -> tuple[str, str]:
    content = fetch(url)
    lowered = content.lower()
    if "<html" not in lowered and "<!doctype html" not in lowered:
        return url, content

    match = RAW_HOSTS_URL_RE.search(content)
    if match is None:
        return url, content

    resolved_url = match.group(0)
    print(f"Resolved raw hosts source: {resolved_url}")
    return resolved_url, fetch(resolved_url)


def normalize_line(line: str) -> str | None:
    line = line.strip()
    if not line or line.startswith("#"):
        return None

    parts = line.split()
    if len(parts) < 2:
        return None

    ip = parts[0].strip()
    host = parts[1].strip().lower()
    if not host or host in {"localhost", "ip6-localhost"}:
        return None
    if not HOSTNAME_RE.fullmatch(host):
        return None

    try:
        ipaddress.ip_address(ip)
    except ValueError:
        return None

    if ip in BLOCK_PREFIXES:
        return f"0.0.0.0 {host}"
    return f"{ip} {host}"


def main() -> int:
    args = parse_args()
    sources = args.sources or DEFAULT_SOURCES
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    merged: list[str] = []
    seen: set[str] = set()

    for source in sources:
        print(f"Loading source: {source}")
        try:
            resolved_source, content = resolve_hosts_content(source)
        except urllib.error.URLError as exc:
            print(f"Failed to load {source}: {exc}", file=sys.stderr)
            return 1

        for raw_line in content.splitlines():
            normalized = normalize_line(raw_line)
            if normalized is None or normalized in seen:
                continue
            seen.add(normalized)
            merged.append(normalized)

    output.write_text(
        "\n".join(
            [
                "# Generated by DnsConf workflow",
                "# Sources:",
                *[f"# {source}" for source in sources],
                *merged,
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Generated {len(merged)} records into {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
